/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackege;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanchit
 */
public class LoginPage extends javax.swing.JFrame {
   int c=0;
    RegisterPage rp=new RegisterPage();
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginHeadLabel = new javax.swing.JLabel();
        LoginUsernameLabel = new javax.swing.JLabel();
        LoginPasswordLabel = new javax.swing.JLabel();
        usernameText1 = new javax.swing.JTextField();
        SubmitLogin = new javax.swing.JButton();
        jumptoRegister = new javax.swing.JButton();
        LoginPassText = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LoginHeadLabel.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        LoginHeadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginHeadLabel.setText("LOGIN");
        getContentPane().add(LoginHeadLabel);
        LoginHeadLabel.setBounds(172, 35, 300, 63);

        LoginUsernameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LoginUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginUsernameLabel.setText("USERNAME");
        getContentPane().add(LoginUsernameLabel);
        LoginUsernameLabel.setBounds(106, 140, 136, 35);

        LoginPasswordLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LoginPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginPasswordLabel.setText("PASSWORD");
        getContentPane().add(LoginPasswordLabel);
        LoginPasswordLabel.setBounds(106, 204, 136, 34);

        usernameText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameText1ActionPerformed(evt);
            }
        });
        getContentPane().add(usernameText1);
        usernameText1.setBounds(394, 142, 175, 35);

        SubmitLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SubmitLogin.setText("SUBMIT");
        SubmitLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitLoginActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitLogin);
        SubmitLogin.setBounds(368, 265, 165, 36);

        jumptoRegister.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jumptoRegister.setText("Don't have an account. Register here.");
        jumptoRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumptoRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jumptoRegister);
        jumptoRegister.setBounds(106, 319, 466, 27);
        getContentPane().add(LoginPassText);
        LoginPassText.setBounds(394, 204, 178, 34);

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(137, 265, 163, 36);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameText1ActionPerformed

    private void jumptoRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumptoRegisterActionPerformed
        // TODO add your handling code here:
        
        rp.setVisible(true);   // jump to Register Page when button clicked
        
        dispose();//Close the current Frame
    }//GEN-LAST:event_jumptoRegisterActionPerformed

    private void SubmitLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitLoginActionPerformed
        // TODO add your handling code here:
        String username1=this.usernameText1.getText();
        String password1=new String(this.LoginPassText.getPassword());
        
        try{
            String url="jdbc:mysql://localhost:3306/CarInfodb";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,"root","1234");
            
            Statement smt=conn.createStatement();
            String sql="select * from ownner1 where username='"+username1+"' and password1='"+password1+"'";
            ResultSet rs=smt.executeQuery(sql);
            
            
            while(rs.next())
            {
               if(username1.equals(rs.getString("username")) && password1.equals(rs.getString("password1"))){
                   c=1;
            }
            }
            if(c==1)
            {
                SearchPage sp=new SearchPage();
            sp.setVisible(true);
            dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Enter Valid Username or Password");
            System.out.println("Error");
            }
        }
        catch(Exception e){
        System.out.println(e);
        }
        
       
    }//GEN-LAST:event_SubmitLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        usernameText1.setText("");
        LoginPassText.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginHeadLabel;
    private javax.swing.JPasswordField LoginPassText;
    private javax.swing.JLabel LoginPasswordLabel;
    private javax.swing.JLabel LoginUsernameLabel;
    private javax.swing.JButton SubmitLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jumptoRegister;
    private javax.swing.JTextField usernameText1;
    // End of variables declaration//GEN-END:variables
}
