/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackege;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JTextField;

/**
 *
 * @author Sanchit
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeadLabel = new javax.swing.JLabel();
        OwnerNameLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        ownernameText = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        middleNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        CarRegNoLabel = new javax.swing.JLabel();
        CarModelLabel = new javax.swing.JLabel();
        CarColourLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        AddressText = new javax.swing.JTextField();
        numberText = new javax.swing.JTextField();
        carRegnoText = new javax.swing.JTextField();
        CarmodelText = new javax.swing.JTextField();
        CarColourText = new javax.swing.JTextField();
        UsernameText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JTextField();
        RegisterSubmit = new javax.swing.JButton();
        jumptologin = new javax.swing.JButton();
        DOBText = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeadLabel.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        HeadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadLabel.setText("REGISTER");

        OwnerNameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        OwnerNameLabel.setText("OWNER'S NAME");

        DOBLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        DOBLabel.setText("DATE OF BIRTH");

        FirstNameLabel.setText("FIRST");

        middleNameLabel.setText("MIDDLE");

        LastNameLabel.setText("LAST");

        AddressLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        AddressLabel.setText("ADDRESS");

        PhoneLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PhoneLabel.setText("PHONE NUMBER");

        CarRegNoLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CarRegNoLabel.setText("CAR REGISTERATION NUMBER");

        CarModelLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CarModelLabel.setText("CAR MODEL");

        CarColourLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CarColourLabel.setText("CAR COLOUR");

        UsernameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        UsernameLabel.setText("USERNAME");

        PasswordLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PasswordLabel.setText("PASSWORD");

        numberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextActionPerformed(evt);
            }
        });

        RegisterSubmit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        RegisterSubmit.setText("SUBMIT");
        RegisterSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterSubmitActionPerformed(evt);
            }
        });

        jumptologin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jumptologin.setText("Already have an account. Click here.");
        jumptologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumptologinActionPerformed(evt);
            }
        });

        DOBText.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(HeadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(RegisterSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jumptologin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CarColourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CarModelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CarRegNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(PhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OwnerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DOBLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ownernameText)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(middleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(AddressText)
                            .addComponent(numberText)
                            .addComponent(carRegnoText)
                            .addComponent(CarmodelText)
                            .addComponent(CarColourText)
                            .addComponent(UsernameText)
                            .addComponent(PasswordText)
                            .addComponent(DOBText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(HeadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ownernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(OwnerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(middleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(DOBText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DOBLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddressText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(AddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(PhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carRegnoText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(CarRegNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CarmodelText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(CarModelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CarColourText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(CarColourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(RegisterSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jumptologin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumptologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumptologinActionPerformed
        // TODO add your handling code here:
        LoginPage lp=new LoginPage();
        lp.setVisible(true);// jump to Login Page when button clicked
        
        dispose();//Close the current Frame
    }//GEN-LAST:event_jumptologinActionPerformed

    private void RegisterSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterSubmitActionPerformed
        // TODO add your handling code here:
        String name1,dob,address,phone_no,reg_no,model,color,username,password;
        name1=this.ownernameText.getText();
        
        address=this.AddressText.getText();
        phone_no=this.numberText.getText();
        reg_no=this.carRegnoText.getText();
        model=this.CarmodelText.getText();
        color=this.CarColourText.getText();
        username=this.UsernameText.getText();
        password=this.PasswordText.getText();
        try{
            String url="jdbc:mysql://localhost:3306/CarInfodb";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,"root","1234");
            
            String query="INSERT INTO ownner1(name1,dob,address,phone_no,reg_no,model,color,username,password1) VALUES(?,?,?,?,?,?,?,?,?)";
            PreparedStatement pstmt=conn.prepareStatement(query);
            
            pstmt.setString(1,name1);
            pstmt.setString(2,((JTextField)DOBText.getDateEditor().getUiComponent()).getText());
            pstmt.setString(3,address);
            pstmt.setString(4,phone_no);
            pstmt.setString(5,reg_no);
            pstmt.setString(6,model);
            pstmt.setString(7,color);
            pstmt.setString(8,username);
            pstmt.setString(9,password);
            pstmt.execute();
            
                   }
        catch(Exception e){
        System.out.println(e);
        }
         
    }//GEN-LAST:event_RegisterSubmitActionPerformed

    private void numberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressText;
    private javax.swing.JLabel CarColourLabel;
    private javax.swing.JTextField CarColourText;
    private javax.swing.JLabel CarModelLabel;
    private javax.swing.JLabel CarRegNoLabel;
    private javax.swing.JTextField CarmodelText;
    private javax.swing.JLabel DOBLabel;
    private com.toedter.calendar.JDateChooser DOBText;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel OwnerNameLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PasswordText;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JButton RegisterSubmit;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JTextField carRegnoText;
    private javax.swing.JButton jumptologin;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField numberText;
    private javax.swing.JTextField ownernameText;
    // End of variables declaration//GEN-END:variables
}
