/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackege;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Sanchit
 */
public class SearchPage extends javax.swing.JFrame {
    int c=0;

    /**
     * Creates new form SearchPage
     */
    public SearchPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfileHeadLabel = new javax.swing.JLabel();
        ProfileCar_noLabel = new javax.swing.JLabel();
        ProfileCar_no = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        ProfileOwnerLabel = new javax.swing.JLabel();
        Profile_name = new javax.swing.JTextField();
        ProfileDOBLabel = new javax.swing.JLabel();
        Profile_DOBText = new javax.swing.JTextField();
        ProfilePhoneLabel = new javax.swing.JLabel();
        Profile_numberText = new javax.swing.JTextField();
        ProfileCarModelLabel = new javax.swing.JLabel();
        ProfileCarColourLabel = new javax.swing.JLabel();
        Profile_carmodelText = new javax.swing.JTextField();
        Profile_carcolourText = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProfileHeadLabel.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        ProfileHeadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileHeadLabel.setText("Profile");

        ProfileCar_noLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ProfileCar_noLabel.setText("CAR REGISTERATION NUMBER");

        ProfileCar_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileCar_noActionPerformed(evt);
            }
        });

        SearchButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SearchButton.setText("SEARCH");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        ProfileOwnerLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ProfileOwnerLabel.setText("OWNER'S NAME");

        ProfileDOBLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ProfileDOBLabel.setText("DATE OF BIRTH");

        ProfilePhoneLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ProfilePhoneLabel.setText("PHONE NUMBER");

        ProfileCarModelLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ProfileCarModelLabel.setText("CAR MODEL");

        ProfileCarColourLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ProfileCarColourLabel.setText("CAR COLOUR");

        UpdateButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ProfileHeadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ProfileCarColourLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProfileCarModelLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProfilePhoneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProfileCar_noLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(ProfileOwnerLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProfileDOBLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Profile_name)
                                    .addComponent(ProfileCar_no, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Profile_DOBText)
                                    .addComponent(Profile_numberText)
                                    .addComponent(Profile_carmodelText)
                                    .addComponent(Profile_carcolourText, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ProfileHeadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(ProfileCar_noLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProfileCar_no, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProfileOwnerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Profile_name, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProfileDOBLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Profile_DOBText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProfilePhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Profile_numberText, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Profile_carmodelText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(ProfileCarModelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProfileCarColourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Profile_carcolourText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(UpdateButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileCar_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileCar_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileCar_noActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String regno=this.ProfileCar_no.getText();
        try{
            String url="jdbc:mysql://localhost:3306/CarInfodb";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,"root","1234");
            
            Statement smt=conn.createStatement();
            String sql="select * from ownner1 where reg_no='"+regno+"'";
            ResultSet rs=smt.executeQuery(sql);
            
            while(rs.next())
            {
            if(regno.equalsIgnoreCase(rs.getString("reg_no")))
            {
                c=1;
            Profile_name.setText(rs.getString("name1"));
            Profile_DOBText.setText(rs.getString("dob"));
            Profile_numberText.setText(rs.getString("phone_no"));
            Profile_carmodelText.setText(rs.getString("model"));
            Profile_carcolourText.setText(rs.getString("color"));
            }
            }
            if(c!=1)
            {
            JOptionPane.showMessageDialog(null,"Enter Valid Car Registeration number");
            }
            
        }
        catch(Exception e)
        {
            
        System.out.println(e);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String name1,dob,phone_no,reg_no,model,color;
        name1=this.Profile_name.getText();
        dob=this.Profile_DOBText.getText();
        phone_no=this.Profile_numberText.getText();
        reg_no=this.ProfileCar_no.getText();
        model=this.Profile_carmodelText.getText();
        color=this.Profile_carcolourText.getText();
        try
        {
            String url="jdbc:mysql://localhost:3306/CarInfodb";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection(url,"root","1234");
            
            String query="update ownner1 set name1='"+name1+"' ,dob='"+dob+"' ,phone_no='"+phone_no+"' ,model='"+model+"' ,color='"+color+"' where reg_no='"+reg_no+"'";
           
            PreparedStatement pstmt=conn.prepareStatement(query);
           
            pstmt.execute();
            JOptionPane.showMessageDialog(null,"Details Updated!!");
        }
        catch(Exception e)
        {
        System.out.println(e);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProfileCarColourLabel;
    private javax.swing.JLabel ProfileCarModelLabel;
    private javax.swing.JTextField ProfileCar_no;
    private javax.swing.JLabel ProfileCar_noLabel;
    private javax.swing.JLabel ProfileDOBLabel;
    private javax.swing.JLabel ProfileHeadLabel;
    private javax.swing.JLabel ProfileOwnerLabel;
    private javax.swing.JLabel ProfilePhoneLabel;
    private javax.swing.JTextField Profile_DOBText;
    private javax.swing.JTextField Profile_carcolourText;
    private javax.swing.JTextField Profile_carmodelText;
    private javax.swing.JTextField Profile_name;
    private javax.swing.JTextField Profile_numberText;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    // End of variables declaration//GEN-END:variables
}
